import {useState,useRef,useEffect} from 'react'
import styles from "../styles/Home.module.css"
import Carousel from '../components/Carousel';
import Separator from "../components/Separator"
import Heading from '../components/Heading';
import Footer from '../components/Footer';
const tvs = [
  {
    name: "Blaupunkt CyberSound",
    image: "/tvs/blaupunkt.png",
    MRP: "24,999",
    price: "19,999",
    rating: "4.4",
  },
  {
    name: "Kodak 4K",
    image: "/tvs/kodak.png",
    MRP: "19,999",
    price: "14,999",
    rating: "4.5",
  },
  {
    name: "Moto Envision",
    image: "/tvs/moto.png",
    MRP: "29,999",
    price: "19,999",
    rating: "4.2",
  },
  {
    name: "Samsung TV",
    image: "/tvs/Samsung.png",
    MRP: "49,999",
    price: "39,999",
    rating: "4.1",
  },
  {
    name: "Moto Envision",
    image: "/tvs/moto.png",
    MRP: "39,999",
    price: "34,999",
    rating: "4.3",
  },
  {
    name: "Thompson TV",
    image: "/tvs/thompson.png",
    MRP: "19,999",
    price: "14,999",
    rating: "4.0",
  },
  {
    name: "Blaupunkt CyberSound",
    image: "/tvs/blaupunkt.png",
    MRP: "24,999",
    price: "19,999",
    rating: "4.6",
  },
  {
    name: "Kodak 4K",
    image: "/tvs/kodak.png",
    MRP: "19,999",
    price: "14,999",
    rating: "4.2",
  },
  {
    name: "Moto Envision",
    image: "/tvs/moto.png",
    MRP: "29,999",
    price: "19,999",
    rating: "4.0",
  },
  {
    name: "Samsung TV",
    image: "/tvs/Samsung.png",
    MRP: "49,999",
    price: "39,999",
    rating: "4.3",
  },
  {
    name: "Moto Envision",
    image: "/tvs/moto.png",
    MRP: "39,999",
    price: "34,999",
    rating: "4.1",
  },
  {
    name: "Thompson TV",
    image: "/tvs/thompson.png",
    MRP: "19,999",
    price: "14,999",
    rating: "4.5",
  },
];
const products = [
  {
    id: 1,
    name:
      "Apple 20W ,USB-C Power Charging Adapter for iPhone, iPad & AirPods  (White)",
    image: "https://rukminim2.flixcart.com/image/416/416/xif0q/battery-charger/u/b/p/-original-imagqjh6gg35h7hz.jpeg?q=70",
    price: 1699,
    MRP: 1900,
    category: "headphones",
    rating: 4.3,
    quantity: 121,
  },
  {
    id: 2,
    name: "2 Pack iPhone Headphones Wired Earbuds with Lightning Connector【MFi Certified】in-Ear Stereo Noise Canceling Isolating Headphones for iPhone 14/13/12/11/SE/X/XR/XS/8 (Built-in Mic & Volume Control)\n4.3 out of 5 stars\n1,757\nINR 1,164.74\nINR1,164\n.\n74\nSave 15% with coupon\nShips to India\nOnly 9 left in stock - order soon.",
    image: "https://m.media-amazon.com/images/I/51pm8Ny6mIL._AC_UY218_.jpg",
    price: 1164,
    MRP: 1300,
    category: "headphones",
    rating: 4.3,
    quantity: 25,
  },
  {
    id: 3,
    name: "2 Pack iPhone Headphones Wired, iPhone Earbuds with Lightning Connector [MFi Certified](Built-in Microphone & Volume Control) Noise Canceling Isolating Headphones for iPhone 14/13/12/11/SE/XS/8/7\n3.9 out of 5 stars\n834\nINR 831.72\nINR831\n.\n72 (INR 416.28/count) List:\nINR 956.60\nINR956.60\nShips to India",
    image: "https://m.media-amazon.com/images/I/41oCxvJdkYL._AC_UY218_.jpg",
    price: 831,
    MRP: 1400,
    category: "headphones",
    rating: 3.9,
    quantity: 57,
  },
  {
    id: 4,
    name: "Earbuds for iPhone Headphones Wired, Earphones with Lightning Connector [MFi Certified] Built-in Microphone & Volume Control, Noise Isolating Headsets for iPhone 14/13/12/11/XR/XS/X/8/7/SE-White\n4.3 out of 5 stars\n8,291\nINR 831.72\nINR831\n.\n72 (INR 139.04/None)\nSave 5% with coupon\nShips to India\nMore Buying Choices\nINR 747.63(2 used & new offers)",
    image: "https://m.media-amazon.com/images/I/41fpTJbMV3L._AC_UY218_.jpg",
    price: 831,
    MRP: 1100,
    category: "headphones",
    rating: 4.3,
    quantity: 121,
  },
  {
    id: 5,
    name: "Peakfun Wireless Headphones Over-Ear Bluetooth Adjustable Headphones 42 Hours of Listening Time Volume Control, Fitting in Gaming/Running/Sports Headphones for iPhone/Android/Samsung - Silver\n4.4 out of 5 stars\n4,312\nINR 3,321.87\nINR3,321\n.\n87\nSave 10% with coupon\nShips to India",
    image: "https://m.media-amazon.com/images/I/71HvuMtsiNL._AC_UY218_.jpg",
    price: 3321,
    MRP: 5500,
    category: "headphones",
    rating: 4.4,
    quantity: 110,
  },
  {
    id: 6,
    name: "Peakfun Pro Wireless Bluetooth Headphones Active Noise Cancelling Over-Ear Headphones with Microphones, 42 Hours Playtime, HiFi Audio Adjustable Headphones for iPhone/Android/Samsung - Silver\n4.1 out of 5 stars\n3,235\nINR 3,155.36\nINR3,155\n.\n36 List:\nINR 4,154.42\nINR4,154.42\nSave 10% with coupon\nShips to India",
    image: "https://m.media-amazon.com/images/I/71HvuMtsiNL._AC_UY218_.jpg",
    price: 3155,
    MRP: 5500,
    category: "headphones",
    rating: 4.1,
    quantity: 47,
  },
  {
    id: 7,
    name: "WASABI MANGO Earbuds for iPhone,Wired Headphones Earphones with Lightning Connector【MFi Certified】 Noise Isolating Headsets for iPhone 14/13/12/11/XR/XS/X/8(Built-in Microphone & Volume Control)\n4.4 out of 5 stars\n1,659\nINR 831.72\nINR831\n.\n72\nSave 5% with coupon\nShips to India",
    image: "https://m.media-amazon.com/images/I/51sQLJYpOlL._AC_UY218_.jpg",
    price: 831,
    MRP: 1200,
    category: "headphones",
    rating: 4.4,
    quantity: 49,
  },
  {
    id: 8,
    name: "Peakfun Wireless Headphones Over-Ear Bluetooth Adjustable Headphones 42 Hours of Listening Time Volume Control, Fitting in Gaming/Running/Sports Headphones for iPhone/Android/Samsung - Space Gary\n4.2 out of 5 stars\n2,822\nINR 3,321.87\nINR3,321\n.\n87 (INR 79.09/None) List:\nINR 4,579.02\nINR4,579.02\nSave 20% with coupon\nShips to India\nOnly 5 left in stock - order soon.",
    image: "https://m.media-amazon.com/images/I/71WKAMxGxRL._AC_UY218_.jpg",
    price: 3321,
    MRP: 4500,
    category: "headphones",
    rating: 4.2,
    quantity: 55,
  },
  {
    id: 9,
    name: "Wired Earbuds for iPhone, Apple Headphones with Lightning Connector [MFi Certified] No Bluetooth Earphones with Microphone & Remote Compatible with iPhone 14/13/12/11/XR/XS/X/8/8Plus/7/SE (White)\n4.8 out of 5 stars\n165\nINR 1,081.48\nINR1,081\n.\n48 List:\nINR 1,664.27\nINR1,664.27\nShips to India",
    image: "https://m.media-amazon.com/images/I/516xM4MPXhL._AC_UY218_.jpg",
    price: 1081,
    MRP: 1499,
    category: "headphones",
    rating: 4.8,
    quantity: 15,
  },
  {
    id: 10,
    name: "Apple Earbuds, 2 Pack iPhone Wired with Lightning Connector [Apple MFi Certified] Wired Earphones with Microphone Volume Control Music and Calling Headphones for iPhone 14/13/12/11/SE/X/XR/XS/8/7\n3.5 out of 5 stars\n519\nINR 790.09\nINR790\n.\n09 (INR 395.46/Count) Typical:\nINR 831.72\nINR831.72\nShips to India",
    image: "https://m.media-amazon.com/images/I/51SYQ4J-+1L._AC_UY218_.jpg",
    price: 790,
    MRP: 999,
    category: "headphones",
    rating: 3.5,
    quantity: 19,
  },
  {
    id: 11,
    name: "[Apple MFi Certified] Wireless Earbuds for AirPods Pro Wireless Headset with Touch Control, Noise Cancelling, IPX7 Waterproof Built-in Microphone with Charging case White\n4.5 out of 5 stars\n5,254\nINR 1,914.03\nINR1,914\n.\n03\nShips to India",
    image: "https://m.media-amazon.com/images/I/51NYfKb0ipL._AC_UY218_.jpg",
    price: 1914,
    MRP: 3500,
    category: "headphones",
    rating: 4.5,
    quantity: 15,
  },
  {
    id: 12,
    name: "Srhythm NiceComfort 95 Hybrid Noise Cancelling Headphones,Wireless Bluetooth Headset with Transparency Mode,HD Sound\n4.2 out of 5 stars\n558\nINR 6,076.78\nINR6,076\n.\n78\nSave 15% with coupon\nShips to India",
    image: "https://m.media-amazon.com/images/I/61lWQaLPqfL._AC_UY218_.jpg",
    price: 6076,
    MRP: 10999,
    category: "headphones",
    rating: 4.2,
    quantity: 121,
  },
  {
    id: 13,
    name: "2 Packs iPhone Earbuds with 3.5mm Plug [iPhone MFi Certified] iPhone Wired Headphones (Built-in Microphone & Volume Control) Compatiable with iPad/iPod/Computer/Laptop/PS5/Most Gaming Audio Devices\n4.6 out of 5 stars\n1,609\nINR 831.72\nINR831\n.\n72\nShips to India",
    image: "https://m.media-amazon.com/images/I/51R5ll3m5dL._AC_UY218_.jpg",
    price: 831,
    MRP: 1299,
    category: "headphones",
    rating: 4.6,
    quantity: 21,
  },
  {
    id: 14,
    name: "2 Pack Wired Apple Earbuds 3.5mm Wired Earbuds Headphones [Apple MFi Certified](Built-in Volume Control & Microphone) Compatible iPhone,iPad,iPod,Computer,MP3/4,Android Most 3.5mm Audio Devices\n4.6 out of 5 stars\n1,554\nINR 1,164.74\nINR1,164\n.\n74 List:\nINR 1,664.27\nINR1,664.27\nShips to India",
    image: "https://m.media-amazon.com/images/I/61FV1mEaR8L._AC_UY218_.jpg",
    price: 1164,
    MRP: 1800,
    category: "headphones",
    rating: 4.6,
    quantity: 32,
  },
  {
    id: 15,
    name: "2 Pack-Apple Earbuds/Lightning/iPhone Headphones Wired Earphones [Apple MFi Certified] Built-in Microphone & Volume Control Compatible with iPhone 7/8/X/11/12/13/14/Pro/Pro Max, Support All iOS System\n2.2 out of 5 stars\n83\nINR 1,163.90\nINR1,163\n.\n90 (INR 581.95/Count) List:\nINR 1,829.11\nINR1,829.11\nShips to India",
    image: "https://m.media-amazon.com/images/I/41h0i8a2fTL._AC_UY218_.jpg",
    price: 1163,
    MRP: 2100,
    category: "headphones",
    rating: 2.2,
    quantity: 27,
  },
  {
    id: 16,
    name: "Sponsored\nHP Newest Flagship 15.6 HD Pavilion Laptop for Business and Student, 16GB RAM, 1TB SSD, Intel Quad-Core Pentium N5030, Webcam, Online Conferencing, Fast Charge, WiFi, Win 11, w/GM Accessory, Black\n4.4 out of 5 stars\n68\nINR 39,046.60\nINR39,046\n.\n60\nShips to India\nOptions:\n8 capacities\n8 capacities",
    image: "https://m.media-amazon.com/images/I/81Jo0-4zMHL._AC_UY218_.jpg",
    rating: 4.4,
    price: 39046,
    MRP: 45799,
    category: "laptops",
    quantity: 27,
  },
  {
    id: 17,
    name: 'Sponsored\nLENOVO IdeaPad 3 Laptop, 15.6" FHD Screen, AMD Ryzen 7 5700U (Beat i7-1160G7), 36GB RAM, 1TB SSD, Webcam, HDMI, Wi-Fi, Windows 11 Pro, Grey\n4.3 out of 5 stars\n9\nINR 58,277.67\nINR58,277\n.\n67\nShips to India\nOptions:\n6 capacities\n6 capacities',
    image: "https://m.media-amazon.com/images/I/71+JttaWXIL._AC_UY218_.jpg",
    rating: 4.3,
    price: 58277,
    MRP: 74499,
    category: "laptops",
    quantity: 27,
  },
  {
    id: 18,
    name: 'Sponsored\nASUS Chromebook Plus CX34 Laptop, 14" Display (1920x1080), Intel® Core™ i3-1215U Processor, 8GB RAM, 256GB UFS Storage, ChromeOS, White, CX3402CBA-DH386-WH\nINR 35,695.58\nINR35,695\n.\n58\nINR 1,986.46 delivery\nShips to India',
    image: "https://m.media-amazon.com/images/I/61MWHGFXhIL._AC_UY218_.jpg",
    rating: 2.1,
    price: 35695,
    MRP: 41999,
    category: "laptops",
    quantity: 27,
  },
  {
    id: 19,
    name: "Sponsored\nBiTECOOL 14-inch Windows 11 Laptop Computer, 12GB RAM 256GB SSD Laptop, Intel Celeron J4005 Dual Core up to 2.7GHz, FHD IPS Display, 2.4G/5G WiFi, BT5.1, Webcam, Lightweight and Portable\n5.0 out of 5 stars\n3\nINR 19,065.40\nINR19,065\n.\n40\nShips to India",
    image: "https://m.media-amazon.com/images/I/711UpSjC0bL._AC_UY218_.jpg",
    rating: 5,
    price: 19065,
    MRP: 25499,
    category: "laptops",
    quantity: 27,
  },
  {
    id: 20,
    name: 'Sponsored\nHP 2022 Stream 14" HD BrightView Laptop, Intel Celeron N4020 Processor, 8GB RAM, 64GB SSD, Intel HD Graphics, 720p Webcam, 1 Year Office 365, Pink, Win 11, 32GB Snowbell USB Card\n4.4 out of 5 stars\n444\nINR 23,228.14\nINR23,228\n.\n14 List:\nINR 24,893.24\nINR24,893.24\nShips to India',
    image: "https://m.media-amazon.com/images/I/51kK0BLesNL._AC_UY218_.jpg",
    rating: 4.4,
    price: 23228,
    MRP: 27999,
    category: "laptops",
    quantity: 27,
  },
  {
    id: 21,
    name: "Sponsored\nHP 15.6 FHD Newest Flagship Business Laptop, Intel 4-Core i3-1215U up to 4.4GHz (Beat i5-1155G7), 16GB RAM, 1TB NVMe SSD, Fast Charge, Numpad, Bluetooth, Wi-Fi, HDMI, Windows 11,w/GM Accessory\n4.4 out of 5 stars\n109\nINR 44,124.32\nINR44,124\n.\n32\nShips to India\nOptions:\n7 capacities\n7 capacities",
    image: "https://m.media-amazon.com/images/I/81QioP9hEjL._AC_UY218_.jpg",
    rating: 4.4,
    price: 44124,
    MRP: 51999,
    category: "laptops",
    quantity: 27,
  },
  {
    id: 22,
    name: "Samsung Galaxy A54 5G A Series Cell Phone, Factory Unlocked Android Smartphone, 128GB w/ 6.4” Fluid Display Screen, Hi Res Camera, Long Battery Life, Refined Design, US Version, 2023, Awesome Black\n4.3 out of 5 stars\n541\nINR 34,133.72\nINR34,133\n.\n72 List:\nINR 37,463.92\nINR37,463.92\nDelivery Mon, Nov 6\nShips to India\nMore Buying Choices\nINR 25,913.12(30 used & new offers)",
    image: "https://m.media-amazon.com/images/I/61MEp5HIdBL._AC_UY218_.jpg",
    price: 34133,
    MRP: 37463.92,
    category: "phones",
    rating: 4.3,
    quantity: 25,
  },
  {
    id: 23,
    name: "Motorola Moto G Stylus 5G | 2021 | 2-Day Battery | Unlocked | Made for US 4/128GB | 48MP Camera | Cosmic Emerald\n4.3 out of 5 stars\n1,339\nINR 12,081.13\nINR12,081\n.\n13\nDelivery Mon, Nov 6\nShips to India\nMore Buying Choices\nINR 9,543.52(23 used & new offers)",
    image: "https://m.media-amazon.com/images/I/51bfhhUKhTL._AC_UY218_.jpg",
    price: 12081,
    MRP: 15463.92,
    category: "phones",
    rating: 4.3,
    quantity: 25,
  },
  {
    id: 24,
    name: "Overall Pick\nMotorola Moto G Stylus | 2022 | 2-Day Battery | Unlocked | Made for US 4/128GB | 50MP Camera | Twilight Blue\n4.3 out of 5 stars\n96\nINR 10,456.83\nINR10,456\n.\n83\nShips to India\nOnly 13 left in stock - order soon.\nMore Buying Choices\nINR 9,989.77(18 used & new offers)",
    image: "https://m.media-amazon.com/images/I/61Q-xaqufQL._AC_UY218_.jpg",
    price: 10456,
    MRP: 12463.92,
    category: "phones",
    rating: 4.3,
    quantity: 25,
  },
  {
    id: 25,
    name: 'Samsung Galaxy A14 4G LTE (128GB + 4GB) Unlocked Worldwide (Only T-Mobile/Mint/Metro USA Market) 6.6" 50MP Triple Camera + (15W Wall Charger) (Silver (SM-A145M/DS))\n4.4 out of 5 stars\n439\nINR 10,989.66\nINR10,989\n.\n66 List:\nINR 11,653.20\nINR11,653.20\nShips to India\nMore Buying Choices\nINR 10,987.99(14 used & new offers)',
    image: "https://m.media-amazon.com/images/I/717yeZFskGL._AC_UY218_.jpg",
    price: 10989,
    MRP: 11653.2,
    category: "phones",
    rating: 4.4,
    quantity: 25,
  },
  {
    id: 26,
    name: "S22 Ultra 6.6 Inch Smartphone, 480x1014 Pixels HD Screen, MTK6580 Quad Core, 2GB RAM 16GB ROM, 2MP 5MP Front Rear Camera, WIFI BT FM GPS Type C Charging, For Android 8.1 Unlocked Cell Phone(Green)\n2.4 out of 5 stars\n8\nINR 9,731.68\nINR9,731\n.\n68\nShips to India\nOnly 12 left in stock - order soon.",
    image: "https://m.media-amazon.com/images/I/71kpOpMpyEL._AC_UY218_.jpg",
    price: 9731,
    MRP: 12463.92,
    category: "phones",
    rating: 2.4,
    quantity: 25,
  },
  {
    id: 27,
    name: "Panasonic Cordless Phone with Answering Machine, Link2Cell Bluetooth, Voice Assistant and Advanced Call Blocking, Expandable System with 4 Handsets - KX-TGD864W (White)\n4.4 out of 5 stars\n319\n1K+ bought in past month\nINR 8,990.71\nINR8,990\n.\n71 List:\nINR 9,989.77\nINR9,989.77\nINR 1,472.78 delivery\nShips to India\nMore Buying Choices\nINR 6,705.36(17 used & new offers)",
    image: "https://m.media-amazon.com/images/I/71EwYZ1t6BL._AC_UY218_.jpg",
    price: 8990,
    MRP: 9989.77,
    category: "phones",
    rating: 4.4,
    quantity: 25,
  },
  {
    id: 28,
    name: "Motorola Moto G Power 5G | 2023 | Unlocked | Made for US 6/256GB | 50 MPCamera | Mineral Black, 163.06 x 74.8 x 8.45mm\n4.0 out of 5 stars\n180\nINR 20,812.92\nINR20,812\n.\n92 List:\nINR 24,975.67\nINR24,975.67\nDelivery Mon, Nov 6\nShips to India\nMore Buying Choices\nINR 15,705.22(17 used & new offers)",
    image: "https://m.media-amazon.com/images/I/61QKKdjHV0L._AC_UY218_.jpg",
    price: 20812,
    MRP: 24975.67,
    category: "phones",
    rating: 4,
    quantity: 25,
  },
  {
    id: 29,
    name: "Samsung Galaxy S23+ Plus Cell Phone, Factory Unlocked Android Smartphone, 256GB, 50MP Camera, Night Mode, Long Battery Life, Adaptive Display, US Version, 2023, Lavender\n4.6 out of 5 stars\n129\nLimited time deal\nINR 74,928.67\nINR74,928\n.\n67 List:\nINR 83,254.17\nINR83,254.17\nINR 1,005.72 delivery\nShips to India\nOptions:\n3 sizes\n3 sizes\nMore Buying Choices\nINR 55,247.19(7 used & new offers)",
    image: "https://m.media-amazon.com/images/I/71LY9chfAKL._AC_UY218_.jpg",
    price: 74928,
    MRP: 83254.17,
    category: "phones",
    rating: 4.6,
    quantity: 25,
  },
  {
    id: 30,
    name: "Samsung Galaxy A53 5G A Series Cell Phone, Factory Unlocked Android Smartphone, 128GB, 6.5” FHD Super AMOLED Screen, Long Battery Life, US Version, Black\n4.3 out of 5 stars\n4,126\nINR 34,092.92\nINR34,092\n.\n92 List:\nINR 37,463.92\nINR37,463.92\nShips to India\nOnly 6 left in stock - order soon.\nClimate Pledge Friendly\nMore Buying Choices\nINR 19,493.33(10 used & new offers)",
    image: "https://m.media-amazon.com/images/I/216-OX9rBaL._SS200_.png",
    price: 34092,
    MRP: 37463.92,
    category: "phones",
    rating: 4.3,
    quantity: 25,
  },
  {
    id: 31,
    name: "Google Pixel 7a - Unlocked Android Cell Phone - Smartphone with Wide Angle Lens and 24-Hour Battery - 128 GB – Charcoal\n4.2 out of 5 stars\n648\nINR 37,381.50\nINR37,381\n.\n50 List:\nINR 41,544.24\nINR41,544.24\nINR 985.74 delivery\nShips to India\nMore Buying Choices\nINR 29,531.38(20 used & new offers)",
    image: "https://m.media-amazon.com/images/I/61r7cCpQPlL._AC_UY218_.jpg",
    price: 37381,
    MRP: 41544.24,
    category: "phones",
    rating: 4.2,
    quantity: 25,
  },
  {
    id: 32,
    name: "AT&T BL102-3 DECT 6.0 3-Handset Cordless Phone for Home with Answering Machine, Call Blocking, Caller ID Announcer, Audio Assist, Intercom, and Unsurpassed Range, Silver/Black\n4.3 out of 5 stars\n23,760\n1K+ bought in past month\nINR 5,824.52\nINR5,824\n.\n52 List:\nINR 7,322.28\nINR7,322.28\nDelivery Tue, Nov 7\nShips to India\nMore Buying Choices\nINR 2,711.62(12 used & new offers)",
    image: "https://m.media-amazon.com/images/I/81xDumBYGBL._AC_UY218_.jpg",
    price: 5824,
    MRP: 7322.28,
    category: "phones",
    rating: 4.3,
    quantity: 25,
  },
  {
    id: 33,
    name: "Total by Verizon TCL 30 Z, 32GB, Black - Prepaid Smartphone (Locked)\n4.0 out of 5 stars\n271\nINR 3,320.21\nINR3,320\n.\n21\nDelivery Mon, Nov 6\nShips to India",
    image: "https://m.media-amazon.com/images/I/718+xprSIBL._AC_UY218_.jpg",
    price: 3320,
    MRP: 5500,
    category: "phones",
    rating: 4.0,
    quantity: 25,
  },
  {
    id: 34,
    name: 'ExAchat A14 5G Unlocked Cell Phones, 6GB + 256GB, 8-Core, 6.82" HD Display Smartphone, Android 13.0, 6000 mAh,64MP + 24MP, Android Phones That Support Face/Fingerprint Recognition-Purple\n2.5 out of 5 stars\n8\nINR 12,487.42\nINR12,487\n.\n42 List:\nINR 13,319.97\nINR13,319.97\nShips to India\nOnly 5 left in stock - order soon.',
    image: "https://m.media-amazon.com/images/I/51W4spsMfNL._AC_UY218_.jpg",
    price: 12487,
    MRP: 13319.97,
    category: "phones",
    rating: 2.5,
    quantity: 25,
  },
  {
    id: 35,
    name: "Motorola Moto G Stylus | 2022 | 2-Day battery | Unlocked| Made for US by Motorola | 6/128GB | 50MP Camera | Twilight Blue\n4.2 out of 5 stars\n2,008\nINR 15,318.09\nINR15,318\n.\n09 List:\nINR 24,975.67\nINR24,975.67\nShips to India\nMore Buying Choices\nINR 9,213.00(26 used & new offers)",
    image: "https://m.media-amazon.com/images/I/612yrAXpo-L._AC_UY218_.jpg",
    price: 15318,
    MRP: 24975.67,
    category: "phones",
    rating: 4.2,
    quantity: 25,
  },
  {
    id: 36,
    name: 'Samsung Galaxy A14 5G A Series Cell Phone, Factory Unlocked Android Smartphone, 64GB w/Expandable Storage, Long Battery Life, 13MP Camera, 6.6" Infinite Display Screen, US Version, 2023, Black\n4.2 out of 5 stars\n524\nINR 16,650.17\nINR16,650\n.\n17\nINR 977.41 delivery\nShips to India\nClimate Pledge Friendly\nMore Buying Choices\nINR 12,101.95(19 used & new offers)\n+1 color/pattern',
    image: "https://m.media-amazon.com/images/I/216-OX9rBaL._SS200_.png",
    price: 16650,
    MRP: 37463.92,
    category: "phones",
    rating: 4.2,
    quantity: 25,
  },
  {
    id: 37,
    name: "Samsung Galaxy A03 Core (SM-A032/DS) Dual SIM 32GB/ 2GB RAM, GSM Unlocked International Version - No Warranty - Black\n3.8 out of 5 stars\n1,783\nINR 7,075.84\nINR7,075\n.\n84\nShips to India\nMore Buying Choices\nINR 6,534.68(18 used & new offers)",
    image: "https://m.media-amazon.com/images/I/61EYfTYzWML._AC_UY218_.jpg",
    price: 7075,
    MRP: 37463.92,
    category: "phones",
    rating: 3.8,
    quantity: 25,
  },
];
const phones = [
  {
    image: "./phones/edge.webp",
    name: "Moto Edge 40, Viva Magenta",
    MRP: "34,999",
    price: "26,999",
    rating: 4.2,
    description:
      "Fuelled with a host of features, this Motorola Edge 40 smartphone brings to you a slim IP68 rated with 30 minutes of underwater dunk resistance. The 3D curved display, bezel-less design, vegan leather option, and sandblasted metal frame add to the phone’s elegance. Powered with a MediaTek 8020 processor, this phone is definitely a game changer. Available with 14 5G bands and WiFi6 networks, experience uninterrupted network connectivity. This phone boasts a 144 Hz 3D curved display and its 1200 nits brightness offers vibrant visuals. Take photography to the next level with the 50 MP main camera with wide aperture of f/1.4 and OIS, 13 MP ultra-wide camera, and 32 MP selfie camera. The 68 W TurboPower charger allows for a quick and full charge in just about ten minutes, and the 4400 mAh battery runs all day with 30 hours of continuous usage. This phone also has the capability of 15W wireless charging for charging on the move. Get a more user-friendly experience with the latest Android 13, and secure your privacy on the phone with the ThinkShield and Moto Secure protective features.",
  },
  {
    image: "./phones/reno.webp",
    name: "OPPO Reno10 5G, Ice Blue",
    MRP: "38,999",
    price: "32,999",
    rating: 4.2,
    description:
      "Explore a range of new features on this Oppo Reno 10 5G smartphone. Capture interesting snaps with the ultra clear Portrait camera. This phone has a 64 MP main camera, 32 MP Telephoto camera, 32 MP selfie camera and a 112 degree wide-angle camera. Make a plethora of possibilities with the Telephoto portrait camera available with this phone. The Pro Portrait Mode lets you capture vivid pictures similar to that of a DSLR camera. This sleek phone weighs only about 185 g and has a 3D curved screen with 120 Hz. Powered with a 5000 mAh battery and 67 W SUPERVOOC charger, this phone runs for an entire day. This Oppo smartphone is equipped with MediaTek Dimensity 7050 SoC Processor and comprises a powerful computing engine. You can explore other features on this phone such as dual stereo speakers, screencast feature, IR remote control, smart AOD functionality and Auto Pixelate for safe file transferring.",
  },
  {
    image: "./phones/pixel.webp",
    name: "Google Pixel 7a, Sea",
    MRP: "43,999",
    price: "35,999",
    rating: 4.1,
    description:
      "Experience the simplicity and seamless transitions with the Google Pixel 7a, which is loaded with a variety of incredible features. The Tensor G2 processor, designed by Google, boosts the Pixel 7a's speed, effectiveness, and security. It's the same chip that's in Pixel 7 and Pixel 7 Pro. Furthermore, With a dual rear camera system and Google Tensor G2's advanced image processing, Pixel 7a lets you create perfect photos every time. It's easy to take amazing pictures in low light, or fix your blurry photos and remove distractions with a few taps in Google Photos. Moreover, the Pixel 7a camera includes Super Res Zoom, so that you can get up close without an extra telephoto lens.",
  },
  {
    image: "./phones/s22.webp",
    name: "Samsung S22 5G, Phantom Black",
    MRP: "85,999",
    price: "39,999",
    rating: 4.4,
    description:
      "Explore a new range of night photography features on this Samsung Galaxy S22 5G smartphone. You can click stunning images even in low light with the Nightography mode. It is designed with a pro-grade camera which comprises a big pixel sensor that welcomes more light for mind-blowing photography. Built with impressive software and hardware, this phone is a game-changer. With a 120 Hz refresh rate and dynamic AMOLED 2x display, you are going to experience immersive screen time. This phone operates on a Snapdragon 8 Gen 1 processor that delivers quick and hassle- free navigation. This device is protected by Corning Gorilla Glass Victus and has an IP68 waterproof rating.",
  },
  {
    image: "./phones/f5.webp",
    name: "POCO F5 5G, Carbon Black",
    MRP: "34,999",
    price: "23,999",
    rating: 4.3,
    description:
      "Experience beastlike performance with the absolutely stunning POCO F5, which is equipped with the King’s Trinity of Performance. The Snapdragon 7+Gen 2 belongs in the same league as the flagship 8 series processors from Snapdragon. The 7+Gen 2 processor from Snapdragon delivers breathtaking performance, leaving you astonished with its processing capability. You can use multiple apps without any lag with 8 GB of RAM and enjoy the liberty of storing enormous media as the phone has up to 256 GB of storage. Your gaming can now be advanced with the striking FEAS 2.2 gaming optimisation tool. The 12-bit panel display offers immersive screen time that is further enhanced with 120 Hz refresh rates. Click awesome pictures with the 7-film camera and a 64 MP triple camera with OIS. The POCO F5 comes with a 4500 mAh battery backup that can charge your phone up to 50% in 12 minutes.",
  },
  {
    image: "./phones/t2.webp",
    name: "vivo T2 Pro 5G, Dune Gold",
    MRP: "26,999",
    price: "23,999",
    rating: 4.3,
    description:
      "The T2 Pro 5G smartphone features a 3D curved AMOLED screen providing a bright display with a peak brightness of 1300 nits. Improve your performance with the MediaTek Dimensity 7200 processor. Powered with a 64 MP main camera with OIS and a night camera with Aura Light, keep clicking stunning pictures all day and night. This smartphone is slim, lightweight and boasts a premium design with AG glass back cover. Available in 8 GB+8 GB RAM, and ROM fused together with an optimised algorithm, you can easily use around 27 apps simultaneously. Powered by a 4600 mAH large battery, you can quickly boost your phone’s charge with the 66 W Flash Charge.",
  },
  {
    image: "./phones/11pro+.webp",
    name: "Realme 11 Pro+ 5G, Oasis Green",
    MRP: "29,999",
    price: "25,999",
    rating: 4.3,
    description:
      "You can capture your memories using the 200 MO OIS SuperZoom camera featured in the realme 11 Pro+ 5G smartphone. The 120 Hz of curved vision display enables you with top-notch viewing experience. Equipped with a 100 W SUPERVOOC charger, this phone charges your phone in about 26 minutes. Powered by the Dimensity 7050 5G chipset, this smartphone offers smooth and efficient performance. Thanks to the 5000 mAh battery, you can go all day long without having to recharge your phone over and over again. This smartphone comes with 12 GB of RAM with an extra 12 GB of dynamic RAM for fast and smooth operations. With the 256 GB of storage, you can store all your data in this smartphone easily.",
  },
  {
    image: "./phones/f54.webp",
    name: "Samsung Galaxy F54 5G, Stardust Silver",
    MRP: "35,999",
    price: "25,999",
    rating: 4.2,
    description:
      "Packed with a myriad of exciting, innovative features, this Samsung Galaxy F54 smartphone is a revolutionary piece of technology. Rise up to your expectations and level up your excitement as this phone is sure to impress you in all its glory. The Nightography mode takes flawless pictures using Pixel Binning and AI technology with its 108 MP camera. No Shake mode caters to the enthusiasm of photo lovers, as you can take incredible photos and videos without any shudder. Moreover, you can take interesting carousel shots, capture impressive pictures in the night with the Astrolapse feature, take beautiful selfies in the dark using the auto night mode, and make your night brighter. Powered by a robust 6000 mAh battery, 5 years of OS and security updates, a smart digital wallet, and a Samsung Exynos 1380 processor, this phone will blow you away with all its revolutionary features. Eco-consciously designed, this phone uses recycled plastic and paper for SIM trays and packaging respectively.",
  },
  {
    image: "./phones/nothing2.webp",
    name: "Nothing Phone (2), Dark Grey",
    MRP: "39,999",
    price: "49,999",
    rating: 4.4,
    description:
      "This premium smartphone is designed with an idea of making it sustainable and be of use to a vast audience. This Nothing Phone (2) has a reduced carbon footprint of 53.45 kg. You get this mobile in a plastic-free packaging and 60% of the paper used comes from recycled sources.",
  },
  {
    image: "./phones/11pro.webp",
    name: "realme 11 Pro 5G, Sunrise Beige",
    MRP: "30,999",
    price: "27,999",
    rating: 4.3,
    description:
      "You can enjoy an immersive display on the 120 Hz curved vision display of the realme Pro 5G smartphone. Featuring a 100 MP OIS ProLight camera, this smartphone allows you to capture memories which you can cherish for a lifetime. This smartphone is powered by the Dimensity 7050 5G chipset for a fast and efficient performance. The 67 W SUPERVOOC charge of this smartphone charges your phone from 0-50% in about 18 minutes so that you do not have to wait long for it to charge. With up to 12 GB + 12 GB of Dynamic RAM, this smartphone ensures smooth and fast operations for you to game and multi-task easily. This smartphone comes with a 5000 mAh battery for a long-lasting battery life.",
  },
  {
    image: "./phones/x5pro.webp",
    name: "POCO X5 Pro 5G, Astral Black",
    MRP: "28,999",
    price: "19,499",
    rating: 4.3,
    description:
      "With the POCO X5 Pro 5G's abundance of exceptional features, enjoy smooth operations and great efficiency. The Snapdragon 778G processor in this smartphone is exceptionally fast and well-optimised. Additionally, it gives you dependable functionality whenever you need it thanks to its astounding 545K AnTuTu score. For an immersive experience, this phone also has a premium-grade AMOLED display and an exceptionally slim bezel. Moreover, this phone's fantastic 108 MP main camera allows you to take stunning photos and enjoy wonderful image processing. This phone's camera also supports 4K video recording at 30 frames per second.",
  },
  {
    image: "./phones/g54.webp",
    name: "MOTOROLA g54 5G, Mint Green",
    MRP: "21,999",
    price: "15,999",
    rating: 4.1,
    description:
      "Stay productive and improve your performance with this resourceful smartphone that has a myriad of features to its name. With 12 GB RAM and 256 GB storage, you can seamlessly perform a multitude of tasks at ease and stack up a heap of content with the huge storage space. The 7020 octa-core MediaTek Dimensity processor delivers a power-packed performance. The 50 MP OIS camera is equipped with Quad Pixel technology and the 16 MP front camera lets you cherish your photography experience. Powered by a 6000 mAh battery supported with a 33 W charger, you can use this mobile for hours together without fearing power drop. With 14 5G bands, experience superfast network connectivity. Experience immersive entertainment with the 120 Hz with 16.6 cm FHD+ Display. Featuring a premium glass finish, stereo speakers with Dolby Atmos and Moto Spatial sound, IP52 rating, this phone lets you have an incredible experience.",
  }
];
const headphones = [
  {
    image: "./headphones/310AP.webp",
    name: "Sony 310AP, Black",
    MRP: "2,190",
    price: "799",
    rating: 4.2,
    description:
      "Just plug in these over-the-head headphones and enjoy listening to music in high clarity wherever you are, and whenever you want. With these headphones in your bag, you can go places without feeling bored as these headphones deliver great music quality.",
  },
  {
    image: "./headphones/CH520.webp",
    name: "Sony WH-CH520, Black",
    MRP: "5,990",
    price: "4,490",
    rating: 4.2,
    description:
      "Combining long-lasting performance with personalised sound quality, the Sony WH-CH520 Wireless Headphones are an excellent addition to your day-to-day life. They boast a playback time of up to 50 hours, making them ideal for long listening sessions. Also, they feature USB Type-C quick charging, providing up to 90 minutes of playback with just 3 minutes of charging time. Moreover, these headphones come with the EQ Custom feature on the Sony Headphones Connect App, allowing you to personalise the sound to suit your preferences.",
  },

  {
    image: "./headphones/CH720N.webp",
    name: "Sony WH-CH720N, Black",
    MRP: "14,990",
    price: "7,990",
    rating: 4.4,
    description:
      "You can experience truly immersive audio on these noise-cancelling Sony headphones. It uses Dual Noise Sensor Technology and Integrated Processor V1 to enhance noise cancelling. These lightweight headphones offer comfort to your ears as you indulge in music for long hours. It uses USB Type-C for quick charging and provides long-lasting battery life of up to 50 hours. These Sony headphones can be connected to two devices at the same time allowing you to switch devices with a single touch.",
  },
  {
    image: "./headphones/770NC.webp",
    name: "JBL Tune 770NC, Black",
    MRP: "9,999",
    price: "5,999",
    rating: 4.2,
    description:
      "Adaptive Noise Cancelling with Smart Ambient :Adaptive Noise Cancelling means zero distractions when it’s time to focus on your studies—or get your groove on. And if you want to hear the world around you without removing your headphones, Ambient Aware and Talk Thru sharpen the sounds of your surroundings or voices. Easily activate these Ambient Sound Control modes through the JBL Headphones app.",
  },
  {
    image: "./headphones/1000XM4.webp",
    name: "Sony WH-1000XM4, Black",
    MRP: "19,999",
    price: "29,999",
    rating: 4.6,
    description:
      "You can enjoy an optimised listening experience with the Sony WH-1000XM4 Bluetooth Headphones. With their Digital Noise Cancellation, these headphones allow you to clearly hear every tune, note, and word with clarity despite your surroundings. Additionally, incorporating Dual Noise Sensor technology and featuring up to two microphones on each earcup, these headphones effectively capture ambient sounds and transmit the data to the HD Noise Cancelling Processor QN1. Also, these headphones provide enhanced call quality through their incorporation of up to five inbuilt microphones and sophisticated audio signal processing technology.",
  },
  {
    image: "./headphones/XB910N.webp",
    name: "Sony WH-XB910N, Black",
    MRP: "19,990",
    price: "11,088",
    rating: 4.4,
    description:
      "Dive deep into music and work whatever you want to concentrate on with the Sony Bluetooth Headset. This headphone comes with an in-built microphone and Bluetooth Connectivity option so that you can enjoy smooth conversations and music flow every day. Moreover, it features Extra Bass technology and a Noise Cancellation feature to provide you with an uninterrupted audio experience.",
  },
  {
    image: "./headphones/551ANC.webp",
    name: "boAt Rockerz 551, Sage Green",
    MRP: "7,990",
    price: "3,499",
    rating: 4,
    description:
      "Hybrid ANC- Say adios to the chaos with Active Noise Cancellation feature and elevate the vibe to a whole new level of pleasure with Rockerz 551ANC, delivering up to 35dB Hybrid ANC.",
  },
  {
    image: "./headphones/760ANC.webp",
    name: "JBL Tune 760NC, Black",
    MRP: "7,999",
    price: "4,499",
    rating: 3.7,
    description:
      "You can listen to your favourite songs in high-quality audio and have clear conversations with the JBL Tune 760NC Wireless Headset. It features Active Noise Cancellation technology, enabling you to listen to music in a noise-free environment. In addition, the long-lasting battery in this headset lets you enjoy its performance without interruptions for up to 50 hours. Furthermore, owing to its wired mode, you can listen to music for as long as you want with the detachable AUX cable.",
  },
  {
    image: "./headphones/800s.webp",
    name: "Sennheiser HD 800s, Black",
    MRP: "39,990",
    price: "25,499",
    rating: 4.5,
    description:
      "Amplify your acoustic experience with this Sennheiser’s Wired Headphone which comes with an innovative sound absorber technology. It has a 56 mm sound transducer and has a stylish design which can make you want to wear it at all times. It also comes with uncovered ear cups that help in providing an enhanced audio experience for you.",
  },
  {
    image: "./headphones/g700.webp",
    name: "Sony Inzone H7 WH-G700, White",
    MRP: "21,990",
    price: "9,990",
    rating: 4.3,
    description:
      "Comfortable enough to wear for hours and with excellent sound quality, the wireless INZONE H7 gaming headset is the perfect partner for any game. Plus, with 360 Spatial Sound for Gaming that lets you hear even more precisely and detect targets or opponents, it'll have your back when you need it.",
  },
  {
    image: "./headphones/HDPHS700.webp",
    name: "Bose HDPHS-700, Silver",
    MRP: "34,990",
    price: "22,990",
    rating: 4.4,
    description:
      "Nothing in the environment will come in the way of you and your music when you are wearing this headset from Bose. This noise-cancelling Bluetooth headset comes with the 4-point Microphone system for effective background noise cancellation. What’s more, you can use simple touch gestures to make any adjustments to your music.",
  },
  {
    image: "./headphones/k72.webp",
    name: "AKG K72, Black",
    MRP: "5,990",
    price: "2,990",
    rating: 4.4,
    description:
      "These AKG Headphones are here to ensure that you get to listen to all your favourite music in style and comfort. The exposed headband design helps keep the headphones light. The earpads are breathable and lightweight and they comfortably sit on your ears. After undergoing different tests, these headphones ensure long-lasting use. With 40 mm drivers, you can enjoy every detail while grooving to your favourite tunes.",
  },
];
const laptops = [
  {
    image: "./laptops/yoga-slim-6.webp",
    name: "Lenovo Yoga Slim 6, Storm Grey",
    MRP: "79,990",
    price: "57,990",
    rating: 4.1,
    description:
      "Ultrathin at 14.9mm & Light from 1.39kg. An all-new design where aesthetic excellence meets curved comfort with the humanized design, all in a smooth and minimalistic finish.",
  },
  {
    image: "./laptops/galaxy-book-2.webp",
    name: "Samsung Galaxy Book2 Pro, Silver",
    MRP: "89,990",
    price: "69,990",
    rating: 4.5,
    description:
      "The world’s thinnest in its class. With plenty of power inside. Galaxy Book2 Pro sacrifices nothing on performance yet weighs in super-light with a slim profile.",
  },
  {
    image: "./laptops/macbook.webp",
    name: "Apple 2022 MacBook Air M2, Midnight",
    MRP: "99,990",
    price: "89,990",
    rating: 4.7,
    description:
      "Charged in a blazing-fast speed with the next-level M2 chip, this redesigned Apple’s notebook comes with mind blowing and has an excellent battery backup that can last up to 18 hours, which comes with an aluminium enclosure.",
  },
  {
    image: "./laptops/hpwith1155G7.webp",
    name: "HP (2023) i5 1155G7, Natural Silver",
    MRP: "64,990",
    price: "52,990",
    rating: 4.7,
    description:
      "8 threads and 8MB L3 cache deliver fast processing speeds and instant responsiveness. The Intel Iris Xᵉ graphics help you dive into crisp, stunning visuals.",
  },
  {
    image: "./laptops/swift3.webp",
    name: "Acer Swift 3 Intel EVO, Lux Gold",
    MRP: "80,990",
    price: "59,990",
    rating: 4.4,
    description:
      "Compact and lightweight, the Acer Swift 3 SF314-71 Laptop is easy to carry along wherever you go. With its up to 2.8K OLED display boasting an aspect ratio of up to 16:10, this laptop ensures high visual quality. In addition, this laptop delivers an immersive experience across a range of activities, including photo editing, movie watching, and enjoying its exceptional contrast and vivid colours. Moreover, equipped with a 12th Gen Intel Core processor, this laptop enhances multitasking capabilities and overall productivity.",
  },
  {
    image: "./laptops/bravo15.webp",
    name: "MSI Bravo 15, Black",
    MRP: "72,990",
    price: "57,990",
    rating: 4.5,
    description:
      "Experience the power of MD Ryzen 5000 Mobile Processor with AMD Radeon RX 6500M Graphics card for immersive gaming. You can connect instantly to the gaming world with WiFi 6E. It has a high refresh rate to provide you with smooth visuals. The thermal solutions for CPU and GPU with CoolerBoost 3 enables you with uninterrupted gaming sessions. It has a wide range of ports so that you can connect multiple devices at the same time.",
  },
  {
    image: "./laptops/inspiron.webp",
    name: "Dell Inspiron, Platinum Silver",
    MRP: "72,990",
    price: "52,990",
    rating: 4.5,
    description: `The speed you need: Featuring 11th Gen Intel Core i5 processor with 512GB SSD storage for a more responsive and quieter performance. Just your type: Get an expansive keyboard with a numeric keypad, 6.4% larger keycaps and a spacious touchpad that makes it easier to navigate your content. All day any day: Work in comfort thanks to a lift hinge that raises your device to an ergonomic angle, which provides a more comfortable typing angle. Easy on the eyes: Dell ComfortView Low Blue Light (LBL) solutions help reduce harmful blue light emissions and optimise eye comfort over extended viewing. More to see: Get more screen in a 15.6" laptop with three-side narrow borders for an immersive FHD viewing experience.`,
  },
  {
    image: "./laptops/pavilion_eyesafe.webp",
    name: "HP Pavilion Eyesafe, Natural Silver",
    MRP: "69,990",
    price: "55,990",
    rating: 4.4,
    description: `You can complete office assignments, watch movies, play games, and do a lot more with the HP Pavilion 14 Laptop. Its high resolution and dynamic colours render life-like images and visuals that provide an engrossing experience. Also, integrated with AMD processors and graphics card, this laptop enables smooth and rapid completion of tasks even while you’re on the go. Moreover, its speaker grill and packaging are made from ocean-bound plastic, which is enduring as well as safe for the environment.`,
  },
  {
    image: "./laptops/gf63.webp",
    name: "MSI GF63, Black",
    MRP: "84,990",
    price: "54,990",
    rating: 4.3,
    description: `The GeForce RTX 30 Series Laptops epitomise outstanding technology, providing unmatched performance for gamers and creators alike. Witness the power of Ampere, combined with RT Cores, Tensor Cores, and streaming multiprocessors, redefining realism and transforming your overall experience. Embrace the cool and collected performance, enjoy up to 7 hours of productivity, and indulge in the world of Hi-Resolution Audio, where music comes alive in its purest form.`,
  },
  {
    image: "./laptops/gf63.webp",
    name: "Asus Vivobook S14, Black",
    MRP: "84,990",
    price: "54,990",
    rating: 4.3,
    description: `The GeForce RTX 30 Series Laptops epitomise outstanding technology, providing unmatched performance for gamers and creators alike. Witness the power of Ampere, combined with RT Cores, Tensor Cores, and streaming multiprocessors, redefining realism and transforming your overall experience. Embrace the cool and collected performance, enjoy up to 7 hours of productivity, and indulge in the world of Hi-Resolution Audio, where music comes alive in its purest form.`,
  },
  {
    image: "./laptops/flow_x13.webp",
    name: "Asus ROG Flow X13, Off Black",
    MRP: "99,990",
    price: "94,990",
    rating: 5,
    description: `The GeForce RTX 30 Series Laptops epitomise outstanding technology, providing unmatched performance for gamers and creators alike. Witness the power of Ampere, combined with RT Cores, Tensor Cores, and streaming multiprocessors, redefining realism and transforming your overall experience. Embrace the cool and collected performance, enjoy up to 7 hours of productivity, and indulge in the world of Hi-Resolution Audio, where music comes alive in its purest form.`,
  },
  {
    image: "./laptops/flow_x13.webp",
    name: "Asus TUF Gaming F15, Graphite Black",
    MRP: "74,990",
    price: "50,990",
    rating: 4.3,
    description: `In the vast sea of gaming laptops, the ASUS TUF Gaming F15 emerges as the beacon of excellence, blending unparalleled power with unmatched durability. Whether you’re a gaming pro or just stepping into the arena, this is the ally you’ve been waiting for. Welcome to the next level.`,
  },
];
const Home = () => {
  return (
    <div className={styles.container}>
      <img className={styles.img} src="/banner.jpg" alt="banner" />
      <Separator />
      <Heading body={"Headphones"} />
      <Carousel data={headphones} />
      <Separator />
      <Heading body={"Phones"} />
      <Carousel data={phones} />
      <Separator />
      <Heading body={"Laptops"} />
      <Carousel data={laptops} />
      <Separator />
      <Heading body={"TVs"} />
      <Carousel data={tvs} />
      <Footer/>
    </div>
  );
}

export default Home
